task: detection

num_classes: 4

train_dataset:
  name: custom_dataset
  img_folder: ./dataset/train
  ann_file: ./dataset/train/_annotations.coco.json
  img_size: 640

val_dataset:
  name: custom_dataset
  img_folder: ./dataset/val
  ann_file: ./dataset/val/_annotations.coco.json
  img_size: 640

dataloader:
  batch_size: 4
  num_workers: 4
  shuffle: true

training:
  epochs: 120
  seed: 42
  print_freq: 10

device: cuda